#!/bin/sh
set -e

# ---- Silent install configuration ----
# All SUITECRM_INSTALL_* variables below are ONLY read once, the first time the
# container starts with an empty app_data volume (no config.php yet) AND
# SUITECRM_SILENT_INSTALL=true. They have no effect on an already-installed
# instance and are not read again afterwards. See README > Silent Install.
SUITECRM_SILENT_INSTALL="${SUITECRM_SILENT_INSTALL:-false}"
SUITECRM_INSTALL_DB_HOST="${SUITECRM_INSTALL_DB_HOST:-db}"
SUITECRM_INSTALL_DB_PORT="${SUITECRM_INSTALL_DB_PORT:-3306}"
SUITECRM_INSTALL_DB_NAME="${SUITECRM_INSTALL_DB_NAME:-suitecrm}"
SUITECRM_INSTALL_DB_USER="${SUITECRM_INSTALL_DB_USER:-suitecrm}"
SUITECRM_INSTALL_DB_PASSWORD="${SUITECRM_INSTALL_DB_PASSWORD:-}"
SUITECRM_INSTALL_SITE_URL="${SUITECRM_INSTALL_SITE_URL:-http://localhost:8080}"
SUITECRM_INSTALL_SYSTEM_NAME="${SUITECRM_INSTALL_SYSTEM_NAME:-SuiteCRM}"
SUITECRM_INSTALL_ADMIN_PASSWORD="${SUITECRM_INSTALL_ADMIN_PASSWORD:-admin}"
SUITECRM_INSTALL_DEMO_DATA="${SUITECRM_INSTALL_DEMO_DATA:-no}"

# Locale / currency (also silent-install-only, applied via config_si.php)
SUITECRM_INSTALL_DEFAULT_LANGUAGE="${SUITECRM_INSTALL_DEFAULT_LANGUAGE:-en_us}"
SUITECRM_INSTALL_DEFAULT_CHARSET="${SUITECRM_INSTALL_DEFAULT_CHARSET:-UTF-8}"
SUITECRM_INSTALL_CURRENCY_NAME="${SUITECRM_INSTALL_CURRENCY_NAME:-US Dollar}"
SUITECRM_INSTALL_CURRENCY_SYMBOL="${SUITECRM_INSTALL_CURRENCY_SYMBOL:-\$}"
SUITECRM_INSTALL_CURRENCY_ISO4217="${SUITECRM_INSTALL_CURRENCY_ISO4217:-USD}"
SUITECRM_INSTALL_CURRENCY_SIGNIFICANT_DIGITS="${SUITECRM_INSTALL_CURRENCY_SIGNIFICANT_DIGITS:-2}"
SUITECRM_INSTALL_NUMBER_GROUPING_SEPARATOR="${SUITECRM_INSTALL_NUMBER_GROUPING_SEPARATOR:-,}"
SUITECRM_INSTALL_DECIMAL_SEPARATOR="${SUITECRM_INSTALL_DECIMAL_SEPARATOR:-.}"
SUITECRM_INSTALL_DISABLE_PERSISTENT_CONNECTIONS="${SUITECRM_INSTALL_DISABLE_PERSISTENT_CONNECTIONS:-false}"

# Start PHP-FPM in background (Alpine uses FPM + Apache proxy_fcgi)
php-fpm -D

if [ -z "$(ls -A /var/www/html 2>/dev/null)" ]; then
    echo "Extracting SuiteCRM to /var/www/html..."
    tmpdir=$(mktemp -d)
    unzip -q -o /usr/src/suitecrm.zip -d "$tmpdir"
    cp -rp "$tmpdir"/*/* /var/www/html/
    rm -rf "$tmpdir"
    echo "SuiteCRM extracted."
fi

if [ ! -f /var/www/html/custom/private.key ] || [ ! -f /var/www/html/custom/public.key ]; then
    echo "Generating RSA keys in /var/www/html/custom/..."
    mkdir -p /var/www/html/custom
    openssl genrsa -out /var/www/html/custom/private.key 2048
    openssl rsa -in /var/www/html/custom/private.key -pubout -out /var/www/html/custom/public.key
    chmod 640 /var/www/html/custom/private.key
    chgrp www-data /var/www/html/custom/private.key /var/www/html/custom/public.key
    echo "Keys generated."
fi

echo "Copying RSA keys to /var/www/html/Api/V8/OAuth2/..."
cp -rp /var/www/html/custom/private.key /var/www/html/Api/V8/OAuth2/
cp -rp /var/www/html/custom/public.key /var/www/html/Api/V8/OAuth2/
echo "Keys copied."

echo "Applying permissions on /var/www/html..."
chown -R www-data:www-data /var/www/html
find /var/www/html -type d -print0 | xargs -0 chmod 755
find /var/www/html -type f -print0 | xargs -0 chmod 644
chmod -R 775 /var/www/html/cache /var/www/html/upload 2>/dev/null || true
chmod 775 /var/www/html/config.php 2>/dev/null || true
echo "Permissions applied."

# ---- Silent install ----
# Uses SuiteCRM's built-in silent installer (config_si.php + install.php?goto=SilentInstall&cli=true).
# Only runs if enabled, and only if SuiteCRM hasn't been installed yet (no config.php).
if [ "$SUITECRM_SILENT_INSTALL" = "true" ] && [ ! -f /var/www/html/config.php ]; then
    echo "Silent install enabled: generating config_si.php..."

    escape_php_string() {
        printf '%s' "$1" | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g"
    }

    db_host_esc=$(escape_php_string "$SUITECRM_INSTALL_DB_HOST")
    db_name_esc=$(escape_php_string "$SUITECRM_INSTALL_DB_NAME")
    db_user_esc=$(escape_php_string "$SUITECRM_INSTALL_DB_USER")
    db_pass_esc=$(escape_php_string "$SUITECRM_INSTALL_DB_PASSWORD")
    site_url_esc=$(escape_php_string "$SUITECRM_INSTALL_SITE_URL")
    system_name_esc=$(escape_php_string "$SUITECRM_INSTALL_SYSTEM_NAME")
    admin_pass_esc=$(escape_php_string "$SUITECRM_INSTALL_ADMIN_PASSWORD")
    demo_data_esc=$(escape_php_string "$SUITECRM_INSTALL_DEMO_DATA")
    default_language_esc=$(escape_php_string "$SUITECRM_INSTALL_DEFAULT_LANGUAGE")
    default_charset_esc=$(escape_php_string "$SUITECRM_INSTALL_DEFAULT_CHARSET")
    currency_name_esc=$(escape_php_string "$SUITECRM_INSTALL_CURRENCY_NAME")
    currency_symbol_esc=$(escape_php_string "$SUITECRM_INSTALL_CURRENCY_SYMBOL")
    currency_iso4217_esc=$(escape_php_string "$SUITECRM_INSTALL_CURRENCY_ISO4217")
    number_grouping_sep_esc=$(escape_php_string "$SUITECRM_INSTALL_NUMBER_GROUPING_SEPARATOR")
    decimal_sep_esc=$(escape_php_string "$SUITECRM_INSTALL_DECIMAL_SEPARATOR")

    cat > /var/www/html/config_si.php <<PHP
<?php
// Generated by docker-entrypoint.sh for silent installation. Removed after use.
\$sugar_config_si = array(
    'setup_db_type' => 'mysql',
    'setup_db_host_name' => '${db_host_esc}',
    'setup_db_port_num' => '${SUITECRM_INSTALL_DB_PORT}',
    'setup_db_database_name' => '${db_name_esc}',
    // The database and DB user are already provisioned (e.g. by the mariadb container),
    // so the installer must not try to create them itself.
    'setup_db_create_database' => false,
    'setup_db_create_sugarsales_user' => false,
    'setup_db_sugarsales_user' => '${db_user_esc}',
    'setup_db_sugarsales_password' => '${db_pass_esc}',
    'setup_db_admin_user_name' => '${db_user_esc}',
    'setup_db_admin_password' => '${db_pass_esc}',
    'demoData' => '${demo_data_esc}',
    'setup_site_url' => '${site_url_esc}',
    'setup_system_name' => '${system_name_esc}',
    'setup_site_admin_user_name' => 'admin',
    'setup_site_admin_password' => '${admin_pass_esc}',
    'setup_license_accept' => true,
    // Locale & currency
    'default_language' => '${default_language_esc}',
    'default_charset' => '${default_charset_esc}',
    'default_currency_name' => '${currency_name_esc}',
    'default_currency_symbol' => '${currency_symbol_esc}',
    'default_currency_iso4217' => '${currency_iso4217_esc}',
    'default_currency_significant_digits' => ${SUITECRM_INSTALL_CURRENCY_SIGNIFICANT_DIGITS},
    'default_number_grouping_seperator' => '${number_grouping_sep_esc}',
    'default_decimal_seperator' => '${decimal_sep_esc}',
    'disable_persistent_connections' => ${SUITECRM_INSTALL_DISABLE_PERSISTENT_CONNECTIONS},
);
PHP
    chown www-data:www-data /var/www/html/config_si.php
    chmod 640 /var/www/html/config_si.php

    echo "Waiting for database ${SUITECRM_INSTALL_DB_HOST}:${SUITECRM_INSTALL_DB_PORT}..."
    attempt=0
    until php -r "exit(@fsockopen('${SUITECRM_INSTALL_DB_HOST}', ${SUITECRM_INSTALL_DB_PORT}) ? 0 : 1);" 2>/dev/null; do
        attempt=$((attempt + 1))
        if [ "$attempt" -ge 30 ]; then
            echo "WARNING: database not reachable after 30 attempts, attempting install anyway." >&2
            break
        fi
        sleep 2
    done

    echo "Starting temporary Apache instance to run the silent installer..."
    httpd -k start

    ready=0
    for _ in $(seq 1 30); do
        if curl -fsS -o /dev/null "http://127.0.0.1/install.php"; then
            ready=1
            break
        fi
        sleep 1
    done

    if [ "$ready" = "1" ]; then
        echo "Running SuiteCRM silent installer..."
        curl -fsS "http://127.0.0.1/install.php?goto=SilentInstall&cli=true" || \
            echo "WARNING: silent install HTTP request failed, check /var/www/html/suitecrm.log" >&2
    else
        echo "WARNING: Apache did not become ready in time, skipping silent install." >&2
    fi

    httpd -k stop
    rm -f /var/www/html/config_si.php

    if [ -f /var/www/html/config.php ]; then
        chown www-data:www-data /var/www/html/config.php
        chmod 775 /var/www/html/config.php
        chown -R www-data:www-data /var/www/html/cache /var/www/html/custom /var/www/html/modules /var/www/html/upload 2>/dev/null || true
        echo "Silent installation completed successfully."
    else
        echo "WARNING: silent installation did NOT produce config.php, check /var/www/html/suitecrm.log" >&2
    fi
fi

exec "$@"