#!/bin/sh
set -e

# ---- Silent install configuration ----
# All SUITECRM_INSTALL_* variables below are ONLY read once, the first time the
# container starts with an empty app_data volume (no config.php yet) AND
# SUITECRM_SILENT_INSTALL=true. They have no effect on an already-installed
# instance and are not read again afterwards. See README > Silent Install.
SUITECRM_SILENT_INSTALL="${SUITECRM_SILENT_INSTALL:-false}"
SUITECRM_INSTALL_DB_HOST="${SUITECRM_INSTALL_DB_HOST:-db}"
SUITECRM_INSTALL_DB_PORT="${SUITECRM_INSTALL_DB_PORT:-3306}"
SUITECRM_INSTALL_DB_NAME="${SUITECRM_INSTALL_DB_NAME:-suitecrm}"
SUITECRM_INSTALL_DB_USER="${SUITECRM_INSTALL_DB_USER:-suitecrm}"
SUITECRM_INSTALL_DB_PASSWORD="${SUITECRM_INSTALL_DB_PASSWORD:-}"
SUITECRM_INSTALL_SITE_URL="${SUITECRM_INSTALL_SITE_URL:-http://localhost:8080}"
SUITECRM_INSTALL_SYSTEM_NAME="${SUITECRM_INSTALL_SYSTEM_NAME:-SuiteCRM}"
SUITECRM_INSTALL_ADMIN_PASSWORD="${SUITECRM_INSTALL_ADMIN_PASSWORD:-admin}"
SUITECRM_INSTALL_DEMO_DATA="${SUITECRM_INSTALL_DEMO_DATA:-no}"

# Locale / currency / date-time (also silent-install-only, applied via config_si.php)
SUITECRM_INSTALL_DEFAULT_LANGUAGE="${SUITECRM_INSTALL_DEFAULT_LANGUAGE:-en_us}"
SUITECRM_INSTALL_DEFAULT_CHARSET="${SUITECRM_INSTALL_DEFAULT_CHARSET:-UTF-8}"
SUITECRM_INSTALL_DEFAULT_DATE_FORMAT="${SUITECRM_INSTALL_DEFAULT_DATE_FORMAT:-m/d/Y}"
SUITECRM_INSTALL_DEFAULT_TIME_FORMAT="${SUITECRM_INSTALL_DEFAULT_TIME_FORMAT:-h:ia}"
SUITECRM_INSTALL_CURRENCY_NAME="${SUITECRM_INSTALL_CURRENCY_NAME:-US Dollar}"
SUITECRM_INSTALL_CURRENCY_SYMBOL="${SUITECRM_INSTALL_CURRENCY_SYMBOL:-\$}"
SUITECRM_INSTALL_CURRENCY_ISO4217="${SUITECRM_INSTALL_CURRENCY_ISO4217:-USD}"
SUITECRM_INSTALL_CURRENCY_SIGNIFICANT_DIGITS="${SUITECRM_INSTALL_CURRENCY_SIGNIFICANT_DIGITS:-2}"
SUITECRM_INSTALL_NUMBER_GROUPING_SEPARATOR="${SUITECRM_INSTALL_NUMBER_GROUPING_SEPARATOR:-,}"
SUITECRM_INSTALL_DECIMAL_SEPARATOR="${SUITECRM_INSTALL_DECIMAL_SEPARATOR:-.}"
SUITECRM_INSTALL_DISABLE_PERSISTENT_CONNECTIONS="${SUITECRM_INSTALL_DISABLE_PERSISTENT_CONNECTIONS:-false}"

# Start PHP-FPM in background (Alpine uses FPM + Apache proxy_fcgi)
php-fpm -D

if [ -z "$(ls -A /var/www/html 2>/dev/null)" ]; then
    echo "Extracting SuiteCRM to /var/www/html..."
    tmpdir=$(mktemp -d)
    unzip -q -o /usr/src/suitecrm.zip -d "$tmpdir"
    cp -rp "$tmpdir"/*/* /var/www/html/
    rm -rf "$tmpdir"
    echo "SuiteCRM extracted."
fi

# Note: it_IT language pack is installed via Module Loader after DB/config.php
# are ready (see post-install block at end of script), not by direct unzip.
# This preserves upgrade_history and Admin > Module Loader visibility.

if [ ! -f /var/www/html/custom/private.key ] || [ ! -f /var/www/html/custom/public.key ]; then
    echo "Generating RSA keys in /var/www/html/custom/..."
    mkdir -p /var/www/html/custom
    openssl genrsa -out /var/www/html/custom/private.key 2048
    openssl rsa -in /var/www/html/custom/private.key -pubout -out /var/www/html/custom/public.key
    chmod 640 /var/www/html/custom/private.key
    chgrp www-data /var/www/html/custom/private.key /var/www/html/custom/public.key
    echo "Keys generated."
fi

echo "Copying RSA keys to /var/www/html/Api/V8/OAuth2/..."
cp -rp /var/www/html/custom/private.key /var/www/html/Api/V8/OAuth2/
cp -rp /var/www/html/custom/public.key /var/www/html/Api/V8/OAuth2/
echo "Keys copied."

echo "Applying permissions on /var/www/html..."
find /var/www/html -path '*/.git' -prune -o -print0 | xargs -0 chown www-data:www-data
find /var/www/html -path '*/.git' -prune -o -type d -print0 | xargs -0 chmod 755
find /var/www/html -path '*/.git' -prune -o -type f -print0 | xargs -0 chmod 644
chmod -R 775 /var/www/html/cache /var/www/html/upload 2>/dev/null || true
chmod 775 /var/www/html/config.php 2>/dev/null || true
echo "Permissions applied."

# ---- Silent install ----
# Uses SuiteCRM's built-in silent installer (config_si.php + install.php?goto=SilentInstall&cli=true).
# Only runs if enabled, and only if SuiteCRM hasn't been installed yet (no config.php).
if [ -f /var/www/html/config.php ]; then cfg_exists=yes; else cfg_exists=no; fi
if [ -z "$(ls -A /var/www/html 2>/dev/null)" ]; then empty=yes; else empty=no; fi
echo "Silent install check: SUITECRM_SILENT_INSTALL=${SUITECRM_SILENT_INSTALL}, config.php exists: $cfg_exists, app_data empty: $empty"
if [ "$SUITECRM_SILENT_INSTALL" = "true" ] && [ ! -f /var/www/html/config.php ]; then
    echo "Silent install enabled: generating config_si.php..."

    # Register the bundled it_IT pack so the installer writes it into the
    # config.php `languages` list (read by install/install_utils.php).
    # Check the bundled zip, not the extracted files (files are installed
    # via Module Loader only after config.php exists).
    if [ -f /usr/src/it_IT.zip ]; then
        cat > /var/www/html/install/lang.config.php <<'PHP'
<?php
// Generated by docker-entrypoint.sh: registers the bundled it_IT language pack
// with the SuiteCRM installer (see install/install_utils.php, handleSugarConfig).
$config['languages'] = array(
    'en_us' => 'English (US)',
    'it_IT' => 'Italiano',
);
PHP
        chown www-data:www-data /var/www/html/install/lang.config.php
        echo "Registered the it_IT language pack with the installer."
    fi

    escape_php_string() {
        printf '%s' "$1" | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g"
    }

    db_host_esc=$(escape_php_string "$SUITECRM_INSTALL_DB_HOST")
    db_name_esc=$(escape_php_string "$SUITECRM_INSTALL_DB_NAME")
    db_user_esc=$(escape_php_string "$SUITECRM_INSTALL_DB_USER")
    db_pass_esc=$(escape_php_string "$SUITECRM_INSTALL_DB_PASSWORD")
    site_url_esc=$(escape_php_string "$SUITECRM_INSTALL_SITE_URL")
    system_name_esc=$(escape_php_string "$SUITECRM_INSTALL_SYSTEM_NAME")
    admin_pass_esc=$(escape_php_string "$SUITECRM_INSTALL_ADMIN_PASSWORD")
    demo_data_esc=$(escape_php_string "$SUITECRM_INSTALL_DEMO_DATA")
    default_language_esc=$(escape_php_string "$SUITECRM_INSTALL_DEFAULT_LANGUAGE")
    default_charset_esc=$(escape_php_string "$SUITECRM_INSTALL_DEFAULT_CHARSET")
    default_date_format_esc=$(escape_php_string "$SUITECRM_INSTALL_DEFAULT_DATE_FORMAT")
    default_time_format_esc=$(escape_php_string "$SUITECRM_INSTALL_DEFAULT_TIME_FORMAT")
    currency_name_esc=$(escape_php_string "$SUITECRM_INSTALL_CURRENCY_NAME")
    currency_symbol_esc=$(escape_php_string "$SUITECRM_INSTALL_CURRENCY_SYMBOL")
    currency_iso4217_esc=$(escape_php_string "$SUITECRM_INSTALL_CURRENCY_ISO4217")
    number_grouping_sep_esc=$(escape_php_string "$SUITECRM_INSTALL_NUMBER_GROUPING_SEPARATOR")
    decimal_sep_esc=$(escape_php_string "$SUITECRM_INSTALL_DECIMAL_SEPARATOR")

    cat > /var/www/html/config_si.php <<PHP
<?php
// Generated by docker-entrypoint.sh for silent installation. Removed after use.
\$sugar_config_si = array(
    'setup_db_type' => 'mysql',
    'setup_db_host_name' => '${db_host_esc}',
    'setup_db_port_num' => '${SUITECRM_INSTALL_DB_PORT}',
    'setup_db_database_name' => '${db_name_esc}',
    // The database and DB user are already provisioned (e.g. by the mariadb container),
    // so the installer must not try to create them itself.
    'setup_db_create_database' => false,
    'setup_db_create_sugarsales_user' => false,
    'setup_db_sugarsales_user' => '${db_user_esc}',
    'setup_db_sugarsales_password' => '${db_pass_esc}',
    'setup_db_admin_user_name' => '${db_user_esc}',
    'setup_db_admin_password' => '${db_pass_esc}',
    'demoData' => '${demo_data_esc}',
    'setup_site_url' => '${site_url_esc}',
    'setup_system_name' => '${system_name_esc}',
    'setup_site_admin_user_name' => 'admin',
    'setup_site_admin_password' => '${admin_pass_esc}',
    'setup_license_accept' => true,
    // Locale, currency & date-time
    'default_language' => '${default_language_esc}',
    'default_charset' => '${default_charset_esc}',
    'default_date_format' => '${default_date_format_esc}',
    'default_time_format' => '${default_time_format_esc}',
    'default_currency_name' => '${currency_name_esc}',
    'default_currency_symbol' => '${currency_symbol_esc}',
    'default_currency_iso4217' => '${currency_iso4217_esc}',
    'default_currency_significant_digits' => ${SUITECRM_INSTALL_CURRENCY_SIGNIFICANT_DIGITS},
    'default_number_grouping_seperator' => '${number_grouping_sep_esc}',
    'default_decimal_seperator' => '${decimal_sep_esc}',
    'disable_persistent_connections' => ${SUITECRM_INSTALL_DISABLE_PERSISTENT_CONNECTIONS},
);
PHP
    chown www-data:www-data /var/www/html/config_si.php
    chmod 640 /var/www/html/config_si.php

    echo "Waiting for database ${SUITECRM_INSTALL_DB_HOST}:${SUITECRM_INSTALL_DB_PORT}..."
    attempt=0
    until php -r "exit(@fsockopen('${SUITECRM_INSTALL_DB_HOST}', ${SUITECRM_INSTALL_DB_PORT}) ? 0 : 1);" 2>/dev/null; do
        attempt=$((attempt + 1))
        if [ "$attempt" -ge 30 ]; then
            echo "WARNING: database not reachable after 30 attempts, attempting install anyway." >&2
            break
        fi
        sleep 2
    done

    echo "Starting temporary Apache instance to run the silent installer..."
    httpd -k start

    ready=0
    for _ in $(seq 1 30); do
        if curl -fsS -o /dev/null "http://127.0.0.1/install.php"; then
            ready=1
            break
        fi
        sleep 1
    done

    if [ "$ready" = "1" ]; then
        echo "Running SuiteCRM silent installer..."
        curl -fsS "http://127.0.0.1/install.php?goto=SilentInstall&cli=true" || \
            echo "WARNING: silent install HTTP request failed, check /var/www/html/suitecrm.log" >&2
    else
        echo "WARNING: Apache did not become ready in time, skipping silent install." >&2
    fi

    httpd -k stop
    rm -f /var/www/html/config_si.php

    if [ -f /var/www/html/config.php ]; then
        chown www-data:www-data /var/www/html/config.php
        chmod 775 /var/www/html/config.php
        chown -R www-data:www-data /var/www/html/cache /var/www/html/custom /var/www/html/modules /var/www/html/upload 2>/dev/null || true
        echo "Silent installation completed successfully."
        cat /var/www/html/config.php | grep -E "default_date_format|default_time_format" | sed 's/^/  config.php: /' || true
    else
        echo "WARNING: silent installation did NOT produce config.php, check /var/www/html/suitecrm.log" >&2
        cat /var/www/html/suitecrm.log 2>/dev/null | tail -n 50 | sed 's/^/  suitecrm.log: /' || true
    fi
fi

# ---- Enforce locale date/time format from env (covers upgrades from image before b7fe1d4) ----
# Silent vars are documented as first-boot-only, but date/time format was added in b7fe1d4;
# existing volumes created with older image would keep m/d/Y. This repair is idempotent
# and ensures compose.it.yml d/m/Y is applied if config still has the old default.
if [ -f /var/www/html/config.php ]; then
    # Wait for DB as well (config exists implies DB should be reachable, but be safe)
    if php -r "exit(@fsockopen('${SUITECRM_INSTALL_DB_HOST}', ${SUITECRM_INSTALL_DB_PORT}) ? 0 : 1);" 2>/dev/null; then
        echo "Ensuring locale date/time format matches env (SUITECRM_INSTALL_DEFAULT_DATE_FORMAT=${SUITECRM_INSTALL_DEFAULT_DATE_FORMAT}, SUITECRM_INSTALL_DEFAULT_TIME_FORMAT=${SUITECRM_INSTALL_DEFAULT_TIME_FORMAT})..."
        cat > /tmp/fix_locale.php <<'PHP'
<?php
define('sugarEntry', true);
chdir('/var/www/html');
require_once 'include/entryPoint.php';
global $sugar_config, $db, $current_user;
// Impersonate admin for preference updates
if (empty($current_user) || !is_admin($current_user)) {
    $admin = BeanFactory::getBean('Users', '1');
    if (empty($admin->id)) {
        $admin = BeanFactory::newBean('Users');
        $admin->retrieve_by_string_fields(['user_name' => 'admin']);
    }
    if (!empty($admin->id)) { $GLOBALS['current_user'] = $current_user = $admin; }
}
$envDate = getenv('SUITECRM_INSTALL_DEFAULT_DATE_FORMAT') ?: 'm/d/Y';
$envTime = getenv('SUITECRM_INSTALL_DEFAULT_TIME_FORMAT') ?: 'h:ia';
$changed = false;
if ($envDate && (!isset($sugar_config['default_date_format']) || $sugar_config['default_date_format'] !== $envDate)) {
    echo "Updating default_date_format: '".($sugar_config['default_date_format']??'unset')."' -> '$envDate'\n";
    $sugar_config['default_date_format'] = $envDate;
    $changed = true;
}
if ($envTime && (!isset($sugar_config['default_time_format']) || $sugar_config['default_time_format'] !== $envTime)) {
    echo "Updating default_time_format: '".($sugar_config['default_time_format']??'unset')."' -> '$envTime'\n";
    $sugar_config['default_time_format'] = $envTime;
    $changed = true;
}
if ($changed) {
    require_once 'modules/Configurator/Configurator.php';
    $cfg = new Configurator();
    $cfg->config['default_date_format'] = $sugar_config['default_date_format'];
    $cfg->config['default_time_format'] = $sugar_config['default_time_format'];
    $cfg->handleOverride();
    echo "config.php/config_override.php updated\n";
} else {
    echo "default_date_format/time_format already correct\n";
}
// Also fix admin user preference 'datef'/'timef' if mismatch (user pref otherwise keeps old m/d/Y)
if (!empty($current_user) && !empty($current_user->id)) {
    $prefDate = $current_user->getPreference('datef');
    $prefTime = $current_user->getPreference('timef');
    echo "Current admin prefs: datef='$prefDate' timef='$prefTime'\n";
    if ($envDate && $prefDate !== $envDate) {
        $current_user->setPreference('datef', $envDate);
        echo "Updated admin datef to $envDate\n";
        $changed = true;
    }
    if ($envTime && $prefTime !== $envTime) {
        $current_user->setPreference('timef', $envTime);
        echo "Updated admin timef to $envTime\n";
        $changed = true;
    }
    if ($changed) { $current_user->savePreferencesToDB(); echo "Admin preferences saved\n"; }
}
PHP
        if id www-data >/dev/null 2>&1; then
            su www-data -s /bin/sh -c "php /tmp/fix_locale.php" || echo "WARNING: locale fix failed" >&2
        else
            php /tmp/fix_locale.php || echo "WARNING: locale fix failed" >&2
        fi
        rm -f /tmp/fix_locale.php
        # Re-apply perms if config changed
        chown www-data:www-data /var/www/html/config.php /var/www/html/config_override.php 2>/dev/null || true
    else
        echo "Skipping locale fix: DB unreachable"
    fi
fi

# ---- Italian language pack via Module Loader ----
# Installs /usr/src/it_IT.zip as if uploaded through Admin > Module Loader,
# so it appears in upgrade_history and Admin > Module Loader.
# Idempotent: skips if already installed. Runs on every boot where config.php
# exists (covers both silent and manual installs, and upgrades of existing volumes).
if [ -f /usr/src/it_IT.zip ] && [ -f /var/www/html/config.php ]; then
    echo "Checking it_IT language pack via Module Loader..."
    # Wait for DB if silent install didn't already do so (manual install case)
    attempt=0
    until php -r "exit(@fsockopen('${SUITECRM_INSTALL_DB_HOST}', ${SUITECRM_INSTALL_DB_PORT}) ? 0 : 1);" 2>/dev/null; do
        attempt=$((attempt + 1))
        if [ "$attempt" -ge 15 ]; then
            echo "WARNING: DB not reachable, skipping Module Loader install for it_IT." >&2
            break
        fi
        sleep 2
    done
    # Only proceed if DB is reachable
    if php -r "exit(@fsockopen('${SUITECRM_INSTALL_DB_HOST}', ${SUITECRM_INSTALL_DB_PORT}) ? 0 : 1);" 2>/dev/null; then
        cat > /tmp/install_it_it.php <<'PHP'
<?php
define('sugarEntry', true);
chdir('/var/www/html');
require_once 'include/entryPoint.php';
require_once 'ModuleInstall/PackageManager/PackageManager.php';
require_once 'modules/Administration/UpgradeHistory.php';

// CLI context has no authenticated user: entryPoint creates an empty $current_user
// Many installer steps (upgrade_custom_relationships, etc.) require is_admin()
// Impersonate the system admin (id=1, user_name=admin) for the install
global $current_user, $sugar_config, $db;
if (empty($current_user) || !is_admin($current_user)) {
    $admin = BeanFactory::getBean('Users', '1');
    if (empty($admin->id)) {
        $admin = BeanFactory::newBean('Users');
        $admin->retrieve_by_string_fields(['user_name' => 'admin']);
    }
    if (!empty($admin->id)) {
        $GLOBALS['current_user'] = $admin;
        $current_user = $admin;
        echo "Impersonating admin user '{$admin->user_name}' ({$admin->id}) for Module Loader install\n";
    } else {
        // Fallback: mock admin to satisfy is_admin() check
        echo "WARNING: admin user not found, forcing is_admin flag\n";
        $current_user->is_admin = 1;
        $GLOBALS['current_user'] = $current_user;
    }
}

$zipSrc = '/usr/src/it_IT.zip';
if (!file_exists($zipSrc)) { echo "it_IT.zip not found, skipping\n"; exit(0); }

$uh = new UpgradeHistory();

// Idempotency: check both DB and filesystem
$hasDbEntry = false;
$result = $db->query("SELECT id, version FROM upgrade_history WHERE id_name='it_IT' AND type='langpack' LIMIT 1");
if ($result) {
    $row = $db->fetchByAssoc($result);
    if (!empty($row['id'])) { $hasDbEntry = true; echo "Found upgrade_history entry for it_IT (version {$row['version']})\n"; }
}
$hasFiles = file_exists('include/language/it_IT.lang.php');

if ($hasDbEntry && $hasFiles) {
    echo "it_IT language pack already installed via Module Loader, skipping.\n";
    // Ensure config.php still has languages entry (installer may have added it, but repair after)
    if (empty($sugar_config['languages']['it_it'])) {
        echo "Adding missing it_it to config.php languages...\n";
        $sugar_config['languages']['it_it'] = 'Italiano';
        require_once 'modules/Configurator/Configurator.php';
        $cfg = new Configurator();
        $cfg->config['languages'] = $sugar_config['languages'];
        // Preserve other overrides
        $cfg->handleOverride();
        echo "config.php languages updated.\n";
    }
    exit(0);
}
if ($hasDbEntry && !$hasFiles) {
    echo "DB entry exists but files missing — will reinstall (removing stale entry).\n";
    $db->query("DELETE FROM upgrade_history WHERE id_name='it_IT' AND type='langpack'");
    $hasDbEntry = false;
}

echo "Installing it_IT language pack via Module Loader...\n";
$pm = new PackageManager();

// Ensure upload dir exists and is writable
$uploadDir = empty($sugar_config['upload_dir']) ? 'upload' : rtrim($sugar_config['upload_dir'], '/\\');
$targetDir = $uploadDir . '/upgrades/langpack';
if (!is_dir($targetDir)) {
    mkdir_recursive($targetDir, true);
}

// Stage via performSetup (validates manifest, copies zip + -manifest.php)
echo "Staging package...\n";
$pm->performSetup($zipSrc, 'module', false);

$targetFile = $targetDir . '/' . basename($zipSrc);
if (!file_exists($targetFile)) {
    echo "performSetup did not create $targetFile, copying manually\n";
    @copy($zipSrc, $targetFile);
    $tmp = $pm->extractManifest($zipSrc, $uploadDir.'/upgrades/temp');
    if ($tmp && file_exists($tmp)) {
        @copy($tmp, preg_replace('/\.zip$/', '-manifest.php', $targetFile));
    }
}
if (!file_exists($targetFile)) {
    echo "ERROR: target file $targetFile missing, aborting\n";
    exit(1);
}
// Patch manifest if image_dir points to non-existent images folder (langpack has no images)
// ModuleInstaller re-reads manifest from the *unzipped* temp dir ($unzip_dir/manifest.php),
// not from $targetFile-manifest.php, so we must patch the manifest *inside* the zip
// and ensure an empty images dir exists, otherwise install_images tries
// dir($unzip_dir/images) -> Warning in include/dir_inc.php:62
$targetManifest = preg_replace('/\.zip$/', '-manifest.php', $targetFile);
if (class_exists('ZipArchive') && file_exists($targetFile)) {
    $za = new ZipArchive();
    if ($za->open($targetFile) === true) {
        $hasImages = false;
        for ($i=0; $i<$za->numFiles; $i++) {
            $name = $za->getNameIndex($i);
            if (strpos($name, 'images/') === 0 || $name === 'images') { $hasImages = true; break; }
        }
        if (!$hasImages) {
            $manifestContent = $za->getFromName('manifest.php');
            if ($manifestContent !== false && (strpos($manifestContent, "'image_dir'") !== false || strpos($manifestContent, '"image_dir"') !== false)) {
                echo "Patching manifest inside zip: removing image_dir (no images in package)\n";
                $patched = preg_replace("/\s*['\"]image_dir['\"]\s*=>\s*['\"][^'\"]*['\"],?\s*\n/", "\n", $manifestContent);
                $za->deleteName('manifest.php');
                $za->addFromString('manifest.php', $patched);
                // keep external -manifest.php in sync for PackageManager's version check
                if (file_exists($targetManifest)) {
                    $ext = file_get_contents($targetManifest);
                    $extPatched = preg_replace("/\s*['\"]image_dir['\"]\s*=>\s*['\"][^'\"]*['\"],?\s*\n/", "\n", $ext);
                    file_put_contents($targetManifest, $extPatched);
                }
            }
            // Add empty images dir so dir() succeeds even if manifest still references it
            if ($za->getFromName('images/') === false) {
                echo "Adding empty images dir to zip to satisfy install_images\n";
                $za->addEmptyDir('images');
            }
        }
        $za->close();
        // Ensure zip is readable by www-data after modification
        @chmod($targetFile, 0644);
    }
}
// ModuleInstaller::install_copy expects $_REQUEST['install_file'] for restore point
$_REQUEST['install_file'] = $targetFile;
$_REQUEST['install_file'] = str_replace('\\','/', $_REQUEST['install_file']);
echo "Running performInstall on $targetFile...\n";
$pm->performInstall($targetFile, true);

if (file_exists('include/language/it_IT.lang.php')) {
    echo "Files installed correctly.\n";
} else {
    echo "WARNING: include/language/it_IT.lang.php not found after install\n";
}

// Ensure languages in config.php
if (empty($sugar_config['languages']['it_it'])) {
    echo "Registering it_it in config.php...\n";
    $sugar_config['languages']['it_it'] = 'Italiano';
    require_once 'modules/Configurator/Configurator.php';
    $cfg = new Configurator();
    $cfg->config['languages'] = $sugar_config['languages'];
    $cfg->handleOverride();
    echo "config.php updated.\n";
}

// Repair
echo "Running Quick RepairAndClear...\n";
require_once 'modules/Administration/QuickRepairAndRebuild.php';
$repair = new RepairAndClear();
$repair->repairAndClearAll(array('clearAll'), array('All'), true, false);
echo "Module Loader installation of it_IT completed.\n";
PHP
        # run as www-data to keep file ownership correct
        if id www-data >/dev/null 2>&1; then
            su www-data -s /bin/sh -c "php /tmp/install_it_it.php" || echo "WARNING: Module Loader install for it_IT failed, check suitecrm.log" >&2
        else
            php /tmp/install_it_it.php || echo "WARNING: Module Loader install for it_IT failed, check suitecrm.log" >&2
        fi
        rm -f /tmp/install_it_it.php
        # fix ownership after install (PackageManager creates files as www-data, but ensure)
        chown -R www-data:www-data /var/www/html/upload 2>/dev/null || true
        chown -R www-data:www-data /var/www/html/cache 2>/dev/null || true
        chown www-data:www-data /var/www/html/config.php 2>/dev/null || true
        chown www-data:www-data /var/www/html/config_override.php 2>/dev/null || true
    else
        echo "Skipping it_IT Module Loader install: DB unreachable."
    fi
fi

exec "$@"