apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: suitecrm

resources:
  - pvc.yaml
  - secret.yaml
  - mariadb.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: suitecrm-database
